// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqKXwJAhgQyQ0uyN9mJ3qoK8n7Q2tyH8',
    appId: '1:466403269362:web:ca41304783065168510e6b',
    messagingSenderId: '466403269362',
    projectId: 'api-afra-ccc99',
    authDomain: 'api-afra-ccc99.firebaseapp.com',
    storageBucket: 'api-afra-ccc99.firebasestorage.app',
    measurementId: 'G-1E554PC3T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcXDVgyntJjUAT3hUrQrhqym1u-oULeU',
    appId: '1:466403269362:android:35752d91841c71ca510e6b',
    messagingSenderId: '466403269362',
    projectId: 'api-afra-ccc99',
    storageBucket: 'api-afra-ccc99.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqKXwJAhgQyQ0uyN9mJ3qoK8n7Q2tyH8',
    appId: '1:466403269362:web:f1c076801e693d62510e6b',
    messagingSenderId: '466403269362',
    projectId: 'api-afra-ccc99',
    authDomain: 'api-afra-ccc99.firebaseapp.com',
    storageBucket: 'api-afra-ccc99.firebasestorage.app',
    measurementId: 'G-8DNVB5CW69',
  );
}
